// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.5.0
// source: XXAACCBB.proto

package xxx

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// XXAACCBBClient is the client API for XXAACCBB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type XXAACCBBClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type xXAACCBBClient struct {
	cc grpc.ClientConnInterface
}

func NewXXAACCBBClient(cc grpc.ClientConnInterface) XXAACCBBClient {
	return &xXAACCBBClient{cc}
}

func (c *xXAACCBBClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/xxx.xxx.XXAACCBB/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// XXAACCBBServer is the server API for XXAACCBB service.
// All implementations must embed UnimplementedXXAACCBBServer
// for forward compatibility
type XXAACCBBServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedXXAACCBBServer()
}

// UnimplementedXXAACCBBServer must be embedded to have forward compatible implementations.
type UnimplementedXXAACCBBServer struct {
}

func (UnimplementedXXAACCBBServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedXXAACCBBServer) mustEmbedUnimplementedXXAACCBBServer() {}

// UnsafeXXAACCBBServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to XXAACCBBServer will
// result in compilation errors.
type UnsafeXXAACCBBServer interface {
	mustEmbedUnimplementedXXAACCBBServer()
}

func RegisterXXAACCBBServer(s grpc.ServiceRegistrar, srv XXAACCBBServer) {
	s.RegisterService(&XXAACCBB_ServiceDesc, srv)
}

func _XXAACCBB_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XXAACCBBServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xxx.xxx.XXAACCBB/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XXAACCBBServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// XXAACCBB_ServiceDesc is the grpc.ServiceDesc for XXAACCBB service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var XXAACCBB_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xxx.xxx.XXAACCBB",
	HandlerType: (*XXAACCBBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _XXAACCBB_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "XXAACCBB.proto",
}
